import localFont from "next/font/local";
import "./globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import AppSidebar from "@/components/AppSidebar";
import TanStackQueryProvider from "@/Providers/TanStackQueryProvider";
import AuthPersistProvider from "@/Providers/AuthPersistProvider";
import { Toaster } from "sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Task Manger App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <AuthPersistProvider> */}
        <TanStackQueryProvider>
          <SidebarProvider>
            <AppSidebar />
            <SidebarTrigger />
            <div className="w-full">
              <Toaster
                richColors
                position="top-center"
                closeButton
              />
              {children}
            </div>
          </SidebarProvider>
        </TanStackQueryProvider>
        {/* </AuthPersistProvider> */}
      </body>
    </html>
  );
}
